### ISSUE TITLE
[Question] Selecting specific modded enemies to use voices and future of the OG version of the mod...

### ISSUE THREAD

**Issue by DatBoi302** [lynxcool/OptimizedSkinwalkers#1]
1) The original version of the mod only allows you to specify which specific vanilla enemies can use the players voices, and if all modded enemies can too. Is there any way or possibility of setting up the config so that we can specify which specific modded enemies we want to be able to use it, instead of just all or nothing? 

2) Is this mod going to be the standard that should be used from now on, instead of the original _SkinWalkers_ mod by Rugbug? Are there any differences other than performance that come with this version?

**Comment by lynxcool** [comment]
Hey there, sorry for the late answer!

1. I did want to future-proof the mod and make it so new enemies would automatically be added to the config list. However I wouldn't be able to guarantee that modded enemies would work too because: 

A) I'm not too familiar with Bepin's launch flow yet and would need to figure out how to force my mod to load last in order to get every enemy type for every modded enemy
B) Because of how I optimized RugBug's mod, every mod maker would need to make sure to add their enemies to the list of enemies once they spawn. If they didn't, then my mod would never pick these enemies up.

2. I wouldn't call my version the _standard_ (I believe Mirage has some more features than mine), but I did add the possibility to use custom audio files alongside/instead of the recorded voices.

If I do end up future-proofing my mod, I'll make sure to check if it works with modded enemies and update my findings on this issue!

**Comment by lynxcool** [comment]
Version 2.0.0 has now released, future proofing the mod.
New enemies will now automatically be added to config files so they can be tweaked individually.

Unfortunately, I didn't find a way to handle modded enemies individually in the same way. However, I added 4 options to help fine tune which enemies we want to make into Skinwalkers and which ones we want to ignore.

I'll be closing this issue, but feel free to open a new one regarding the handling of individual modded enemies (in case somebody with more knowledge than me wishes to help!)
