### ISSUE TITLE
Logs spam

### ISSUE THREAD

**Issue by Alyaqdhans** [lynxcool/OptimizedSkinwalkers#2]
Getting spammed logs every frame to the point of lag spikes

Edit: I think this is because it can't find any monster to put the voice on maybe? because I disabled all of them except the masked and they might have not spawned in the moon we are in.
![image](https://github.com/user-attachments/assets/a0942a8c-b197-4a6a-8b8c-255a5db4f94c)

**Comment by Alyaqdhans** [comment]
I don't know if it's relevent or not but I have some performance mods like pathfindingfix

**Comment by Alyaqdhans** [comment]
I think I have found out the cause of it, it's an entty called shrimp from LCOffice mod, I didn't ever seen it yet until now.

**Comment by Alyaqdhans** [comment]
By the way, I'm using the skinwalkers mod for just the masked enemy. If possible to request a feature that you can disable all mosters except something. Like this:
- Disable all mosters: true/false
- Disable exception: monster1, moster2, ...etc

**Comment by lynxcool** [comment]
Hey there! I'll look into it, but this is an odd issue that didn't happen on my end when playing. Do you have other mods that you suspect may cause this? (Like an enemy mod)?

As for your suggestion, I can't exactly have both "enable these monsters" and "disable these monsters" as options, since you could make them conflict in the config. Though you could toggle the enemies pretty easily using a note pad application instead of r2modman.

**Comment by Alyaqdhans** [comment]
Not very sure but it might be the shrimp from LC Office mod, although I disabled the whole LC Office mod and it still occurred sometimes, for now I'm using Mirage mod it seems stable.

**Comment by lynxcool** [comment]
I uploaded version 2.2.0 with a fix attempt. If you end up reusing Optimized Skinwalkers, let me know if this issue still happens!

**Comment by Alyaqdhans** [comment]
Unfortunately, the fix didn't work. So I noticed that it starts to error when you first land on a moon and it detects a voice. If you want to try and debug it here is the profile code before I change any mods (the first time I saw the error).
Code: `01918aa8-1d97-e147-73ec-fc4d3ea6d851`

I didn't update any mods so that it stays the way I first found the bug, although I think I tried with everything updated and no hope, good luck on this!

If you want to test anything or ask something, do not hesitate, I'm a developer too (with basic coding knowledge), but know nothing in Unity.

**Comment by Alyaqdhans** [comment]
> Hey there! I'll look into it, but this is an odd issue that didn't happen on my end when playing. Do you have other mods that you suspect may cause this? (Like an enemy mod)?
> 
> As for your suggestion, I can't exactly have both "enable these monsters" and "disable these monsters" as options, since you could make them conflict in the config. Though you could toggle the enemies pretty easily using a note pad application instead of r2modman.

About the suggestion, you can implement it and mention that the "disable all" option takes priority over the top toggles (or bottom if you made it at the top), in other words, it will be 2 sections the toggles or the disable all with the exceptions.
Or if you want an easier implementation make a "Reverse toggles" option.

I'm asking for this so that if any monsters are added, the mod disables them on its own instead of having the trouble to tweak the config every time the game or the mods had a new enemy. You can also default the new enemies to false if this suggestion seems too much (just like "Mirage" mod all false except mask by default). Or you can also make a "default new enemies to true" toggle.
--I know I seem to be crazy, but I just care about every small detail, sorry for that :)

**Comment by lynxcool** [comment]
I haven't looked at the code just yet, but I'm starting to suspect the mod's config could be related somehow. Could you send me your config file for optimized skinwalkers? (or copy paste the text, that also works!)

As for your suggestion, I don't think you're crazy, I'm also a big fan of UX! I just want to make sure the config settings are instinctive out of the box!
I don't think I'd disable all by default, to keep Rugbug's original mod behaviour (that's why I enable new enemies by default), but an "Inverse toggle" makes a lot of sense!

**Comment by Alyaqdhans** [comment]
modified the extension because of Github restriction
[lynxdev.OptimizedSkinwalkers.cfg.txt](https://github.com/user-attachments/files/16741384/lynxdev.OptimizedSkinwalkers.cfg.txt)

**Comment by lynxcool** [comment]
Alright, this took me way too long to figure out, but this should be fixed with version 2.3.0!

My guess is, one of the mods installed is clearing the events subscribed to SceneManager.sceneLoaded, which prevents the SkinwalkerNetworkManager from being initialized.

Another thing that seems to be happening, is that the scene containing the object with SkinwalkerNetworkManager gets destroyed while we load inside the ship.

I fixed this by changing the loading process and then making the SkinwalkerNetworkManager DontDestroyOnLoad. My only worry is that it might mess with the configuration if every client doesn't have the same config and the host swaps around in the same game session.

I hope I wasn't too unclear! If you get any other issue, let me know!

(I'll probably implement your suggestion later this week!)

**Comment by Alyaqdhans** [comment]
Did you know which mod caused that? I think this bug was happening from the original Skinwalkers mod, not because of you. Does the new version require a new config? Also, I wanted to ask a modder for a long time, isn't there a way in the code to reinitialize the config file so that users don't need to worry about anything? (while keeping the user settings) maybe it's possible by detecting the file date? I kind of understand why no one bothers to do something complicated about the config file, it's a headache.

**Comment by lynxcool** [comment]
There was bit too many mods for me to figure out which one was causing the issue, so I opted to just fix it instead! You could probably figure out which one it was by trial and error, but I don't think there's another way (but I'm not sure).

I used to initialize the NetworkManager the same way Rugbug did in his version, so the issue would definitely happen on both.

I think I saw somewhere in Bepin's doc that there's a way to remove unused configs, but I think it was deprecated? I'd have to look it up again.

Unfortunately, I have experience with Unity but next to none with Bepin, so I have to learn as I go ^^"

**Comment by Alyaqdhans** [comment]
I think the issue is fixed! you can close the issue anytime you want.

One more question, what do I do when I have found a bug on mods that don't have Github? here some:
- Backrooms (monster doesn't kill)
- Modded moons (the dropship is bugged)
- BetterSaves (doesn't highlight the last used file)

(I think most of them broke from the last update.)
And many more, I'm kind of a good bug spotter, but I can't find a way to reach to the developers sometimes.

Thank you for your time, and sorry if I took much from your time, I'm much of a talker about UX and bugs.

**Comment by lynxcool** [comment]
No worries! Thank you for your assistance! My ultimate goal is for this mod to be future-proof and to work regardless of what other mods run with it!

There is a modding Discord for Lethal Company. Some mod devs are available there, but other users also often have solutions!

https://discord.com/invite/lcmod
